version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - reverse-proxy
    depends_on:
      - web
      - api
    volumes:
      - ./ops/nginx/svr-includes:/etc/nginx/svr-includes:ro

  web:
    image: collinbarrett2/filterlists.web:latest
    restart: always
    build:
      context: ./web
      target: final
    networks:
      - reverse-proxy

  api:
    image: collinbarrett2/filterlists.api:latest
    restart: always
    build:
      context: .
      dockerfile: server/src/FilterLists.Api/Dockerfile
      target: final
    networks:
      - reverse-proxy
      - db
    depends_on:
      - db
    environment:
      ConnectionStrings__FilterListsConnection: ${API_CONNECTION_STRING}

  db:
    # on update, also update ServerVersion in FilterLists.Data.Constants.ServerVersion
    image: mariadb:10.5.4
    restart: always
    networks:
      - db
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${API_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${API_MYSQL_DATABASE}
      MYSQL_USER: ${API_MYSQL_USER}
      MYSQL_PASSWORD: ${API_MYSQL_PASSWORD}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_520_ci",
      ]

networks:
  reverse-proxy:
  db:

volumes:
  data:
